"""
Django settings for the project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# [SECURITY] Domain and Site Name masked for portfolio
SITE_URL = config('SITE_URL', default='http://localhost:8000')
SITE_NAME = config('SITE_NAME', default='My Ecommerce Project')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']

# [SECURITY] Third-party integration keys (Shipping, Payments, etc.)
# Logic flow and specific provider credentials have been removed.
SHIPROCKET_CONFIG = {
    'EMAIL': config('SHIPROCKET_EMAIL', default='hidden'),
    'PASSWORD': config('SHIPROCKET_PASSWORD', default='hidden'),
    'PICKUP_PINCODE': config('SHIPROCKET_PINCODE', default='000000')
}

RAZORPAY_CONFIG = {
    'KEY_ID': config('RAZORPAY_KEY_ID', default='hidden'),
    'KEY_SECRET': config('RAZORPAY_KEY_SECRET', default='hidden'),
    'CURRENCY': 'INR'
}

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.provider.com')
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='hidden@example.com')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='hidden')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Application definition
SITE_ID = 1
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Custom Apps
    'mainapp',
    'adminapp',

    # Third-Party Apps
    'rest_framework',
    'django_recaptcha',
    'storages',
    'django_ratelimit',
    'django_celery_beat',
    'django.contrib.sites',
    'django.contrib.sitemaps',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# [SECURITY] Search Engine Configuration
MEILISEARCH = {
    'HOST': config('MEILISEARCH_HOST', default='http://search-engine:7700'),
    'MASTER_KEY': config('MEILI_MASTER_KEY', default='hidden_master_key'),
    'TIMEOUT': 10
}

# CSRF Settings
CSRF_COOKIE_NAME = "csrftoken"
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=True, cast=bool)
CSRF_COOKIE_HTTPONLY = False

# reCAPTCHA Keys
RECAPTCHA_PUBLIC_KEY = config('RECAPTCHA_PUBLIC_KEY', default='hidden_site_key')
RECAPTCHA_PRIVATE_KEY = config('RECAPTCHA_PRIVATE_KEY', default='hidden_secret_key')
AUTH_KEY = config('AUTH_KEY', default='hidden_internal_auth_key')

ROOT_URLCONF = 'twentyfivefirst.urls'

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'auth.log'),
        },
    },
    'loggers': {
        'auth': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# [SECURITY] Redis Cache Configuration
# Internal Redis routing and DB partitioning logic preserved but generalized.
REDIS_HOST = os.getenv("REDIS_HOST", "redis-broker")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "hidden_password")

REDIS_DB_CACHE = os.getenv("REDIS_DB_CACHE", "1")
REDIS_DB_SESSIONS = os.getenv("REDIS_DB_SESSIONS", "2")

REDIS_URL_CACHE = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_CACHE}"
REDIS_URL_SESSIONS = f"redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB_SESSIONS}"

CACHES = {
    # General application cache
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL_CACHE,
        "KEY_PREFIX": "project_cache:",
        "TIMEOUT": 300,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100, "retry_on_timeout": True},
        },
    },
    # Dedicated cache for Django sessions
    "sessions": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL_SESSIONS,
        "KEY_PREFIX": "project_sess:",
        "TIMEOUT": None,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 100, "retry_on_timeout": True},
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
    },
}

# Use Redis-backed sessions
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "sessions"
SESSION_SERIALIZER = "django.contrib.sessions.serializers.JSONSerializer"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30
SESSION_SAVE_EVERY_REQUEST = True 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'twentyfivefirst.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='dummy_db'),
        'USER': config('DB_USER', default='dummy_user'),
        'PASSWORD': config('DB_PASSWORD', default='dummy_password'),
        'HOST': config('DB_HOST', default='db_host'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator' },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator' },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'mainapp' / "static",
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Login/Logout Redirects
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# [SECURITY] Storage / Object Storage Configuration
# Replaced specific S3/MinIO endpoint with generic configuration structure
DEFAULT_FILE_STORAGE = 'storages.backends.s3.S3Storage'

AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID', default='hidden_key')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY', default='hidden_secret')
AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME', default='media-bucket')
AWS_S3_ENDPOINT_URL = config('AWS_S3_ENDPOINT_URL', default='https://s3.provider.com')
AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME', default='us-east-1')
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_QUERYSTRING_AUTH = False
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_S3_USE_SSL = config('AWS_S3_USE_SSL', default=True, cast=bool)
MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/"

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "region_name": AWS_S3_REGION_NAME,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "addressing_style": AWS_S3_ADDRESSING_STYLE,
            "default_acl": AWS_DEFAULT_ACL,
            "use_ssl": AWS_S3_USE_SSL,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# [SECURITY] Celery Configuration
# Broker details masked
CELERY_BROKER_HOST = os.getenv("REDIS_HOST", "redis-broker")
CELERY_BROKER_PORT = os.getenv("REDIS_PORT", "6379")
CELERY_BROKER_PASSWORD = os.getenv("REDIS_PASSWORD", "hidden_password")
CELERY_REDIS_DB = os.getenv("REDIS_DB_CELERY", "4")
CELERY_BROKER_URL = f"redis://:{CELERY_BROKER_PASSWORD}@{CELERY_BROKER_HOST}:{CELERY_BROKER_PORT}/{CELERY_REDIS_DB}"
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)

CELERY_TASK_DEFAULT_QUEUE = "default"
CELERY_TASK_QUEUES = {
    "default": {"binding_key": "default"},
    "emails": {"binding_key": "emails"},
}
CELERY_TASK_DEFAULT_EXCHANGE = "celery"
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_SOFT_TIME_LIMIT = 300
CELERY_TIMEZONE = "Asia/Kolkata"

from celery.schedules import crontab

# [SECURITY] Periodic Tasks
# Specific business logic tasks (e.g., cart retention strategies) are hidden.
CELERY_BEAT_SCHEDULE = {
    'maintenance-task-example': {
        'task': 'mainapp.tasks.general.maintenance',
        'schedule': crontab(minute='*/30'),
    },
    # Additional proprietary scheduled tasks hidden
}